Algoritmo "Projeto Github"

Inicio

   escreval
   escreval ("CRIAÇÃO DE REPOSITÓRIO NO GITHUB")
   escreval
   escreval ("Passo a passo: Salvar primeira versão de um projeto no Github")
   escreval
   escreval ("Configuração de ambiente:")
   escreval ("1. Usuário")
   escreval ("2. Email")
   escreval ("3. Visualizar arquivos ocultos")
   escreval ("4. Chave SSH")



   escreval
   escreval

Fimalgoritmo